// Code generated by mockery v1.0.0
package communication_mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: id, locale, email, params
func (_m *Application) SendEmail(id string, locale string, email string, params map[string]interface{}) error {
	ret := _m.Called(id, locale, email, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, map[string]interface{}) error); ok {
		r0 = rf(id, locale, email, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendSms provides a mock function with given fields: id, locale, number, params
func (_m *Application) SendSms(id string, locale string, number string, params map[string]interface{}) error {
	ret := _m.Called(id, locale, number, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, map[string]interface{}) error); ok {
		r0 = rf(id, locale, number, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields: ctx
func (_m *Application) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}
